// `.env.ts` is generated by the `npm run env` command
import env from './.env';
export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '/MoonBox/Demo/',
  moonBoxBackendUrl: '/MoonBox/Demo/backend/',
  moonBoxBackendDomain: 'monwoo.com',
  moonBoxBackendBasePath: '/MoonBox/Demo/backend/'
};
